# --- Font ---
#font_family      JetBrainsMono Nerd Font
font_family      AdwaitaMono Nerd Font Mono
#font_family      DejaVu Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11

# --- Theme (simple dark) ---
#background       #1e1e2e
background       #000000
#foreground       #cdd6f4
foreground       #eeeeee

# Cursor
cursor           #f5e0dc
cursor_text_color #1e1e2e

# Selection
selection_background #585b70
selection_foreground #cdd6f4

# --- Basic usability ---
enable_audio_bell no
confirm_os_window_close 0

# Optional: slightly transparent background
background_opacity 0.70
